name: Default
description: The default issue template for this project
body:
  - type: markdown
    attributes:
      value: |
        ## Default issue template
        This is the default issue template for this project
